"use client";
import { useEffect,useMemo,useState } from "react";
type Item={id:string;module:string;data:Record<string,string|number>;updatedAt:string};
type Key="painel"|"obras"|"trabalhadores"|"equipamentos"|"materiais"|"movimentacoes"|"documentos"|"impedimentos"|"utilizadores"|"relatorios";
const config:Record<Exclude<Key,"painel"|"relatorios">,{title:string;singular:string;fields:string[]}> = {
 obras:{title:"Obras",singular:"obra",fields:["nome","local","provincia","estado","progresso","responsavel","trabalhadores","orcamento","gasto"]},
 trabalhadores:{title:"Recursos Humanos",singular:"trabalhador",fields:["nome","categoria","funcao","afectacao","provincia","contacto","estado"]},
 equipamentos:{title:"Equipamentos",singular:"equipamento",fields:["codigo","nome","tipo","afectacao","estado"]},
 materiais:{title:"Materiais",singular:"material",fields:["codigo","nome","unidade","quantidade","local"]},
 movimentacoes:{title:"Movimentações",singular:"movimentação",fields:["data","recurso","origem","destino","motivo"]},
 documentos:{title:"Gestão Documental",singular:"documento",fields:["codigo","titulo","categoria","obra","versao","responsavel","estado"]},
 impedimentos:{title:"Ocorrências Disciplinares",singular:"ocorrência",fields:["trabalhador","tipo","data","descricao","decisao","estado"]},
 utilizadores:{title:"Utilizadores",singular:"utilizador",fields:["nome","email","perfil","estado"]},
};
const labels:Record<Key,string>={painel:"Painel",obras:"Obras",equipamentos:"Equipamentos",materiais:"Materiais",trabalhadores:"Recursos Humanos",movimentacoes:"Movimentações",documentos:"Gestão Documental",impedimentos:"Ocorrências",utilizadores:"Utilizadores",relatorios:"Relatórios"};
const order:Key[]=["painel","obras","equipamentos","materiais","trabalhadores","movimentacoes","documentos","impedimentos","utilizadores","relatorios"];
const money=(v:number)=>new Intl.NumberFormat("pt-MZ",{style:"currency",currency:"MZN",maximumFractionDigits:0}).format(v);
export default function GestaoClient(){
 const [active,setActive]=useState<Key>("painel"),[items,setItems]=useState<Item[]>([]),[role,setRole]=useState(""),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[q,setQ]=useState("");
 async function load(){setLoading(true);const r=await fetch("/api/gestao",{cache:"no-store"});if(r.ok){const x=await r.json();setItems(x.items);setRole(x.role)}else setMessage("A sua conta ainda não foi autorizada pelo Administrador.");setLoading(false)}
 useEffect(()=>{load()},[]);
 const rows=useMemo(()=>items.filter(i=>i.module===active&&JSON.stringify(i.data).toLowerCase().includes(q.toLowerCase())),[items,active,q]);
 const obras=items.filter(i=>i.module==="obras"),canSeeMoney=["ceo","administrador"].includes(role);
 const activeWorks=obras.filter(i=>!String(i.data.estado).toLowerCase().includes("conclu")),workers=obras.reduce((n,i)=>n+Number(i.data.trabalhadores||0),0),avg=activeWorks.length?Math.round(activeWorks.reduce((n,i)=>n+Number(String(i.data.progresso||0).replace("%","")),0)/activeWorks.length):0;
 async function add(){if(active==="painel"||active==="relatorios")return;const c=config[active],data:Record<string,string>={};for(const f of c.fields){const v=prompt(`${f[0].toUpperCase()}${f.slice(1)}:`);if(v===null)return;data[f]=v}await save("/api/gestao","POST",{module:active,data},"Registo guardado.")}
 async function edit(item:Item){const c=config[active as Exclude<Key,"painel"|"relatorios">],data={...item.data};for(const f of c.fields){const v=prompt(`${f[0].toUpperCase()}${f.slice(1)}:`,String(data[f]??""));if(v===null)return;data[f]=v}await save(`/api/gestao/${item.id}`,"PUT",{module:active,data},"Registo actualizado.")}
 async function save(url:string,method:string,body:unknown,ok:string){const r=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setMessage(r.ok?ok:"Operação recusada. Confirme a sua permissão.");if(r.ok)await load()}
 async function remove(item:Item){if(!confirm("Confirma que pretende apagar este registo?"))return;const r=await fetch(`/api/gestao/${item.id}`,{method:"DELETE"});setMessage(r.ok?"Registo apagado.":"Não foi possível apagar.");if(r.ok)await load()}
 function exportar(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(items,null,2)],{type:"application/json"}));a.download="base-khuumba.json";a.click()}
 return <div className="restored-shell"><aside className="restored-nav"><div><small>GESTÃO INTEGRADA</small><strong>{role||"Utilizador"}</strong></div>{order.map(k=><button className={active===k?"active":""} onClick={()=>setActive(k)} key={k}>{labels[k]}</button>)}</aside><section className="restored-main"><header className="restored-header"><div><p className="eyebrow">PLATAFORMA KHUUMBA · BASE CENTRAL</p><h1>{labels[active]}</h1></div><div className="restored-actions"><input placeholder="Pesquisar…" value={q} onChange={e=>setQ(e.target.value)}/><button onClick={exportar}>Exportar base ↓</button></div></header>{message&&<p className="management-message">{message}</p>}{loading?<div className="data-card">A carregar dados…</div>:active==="painel"?<><div className="dashboard-kpis"><article><small>OBRAS ACTIVAS</small><strong>{activeWorks.length}</strong><span>{obras.length-activeWorks.length} concluídas</span></article><article><small>PROGRESSO MÉDIO</small><strong>{avg}%</strong><span>Obras em curso</span></article><article><small>TRABALHADORES</small><strong>{workers}</strong><span>Afectos às obras</span></article><article><small>EQUIPAMENTOS</small><strong>{items.filter(i=>i.module==="equipamentos").length}</strong><span>Inventário registado</span></article>{canSeeMoney&&<article className="financial-kpi"><small>VALOR GASTO</small><strong>{money(obras.reduce((n,i)=>n+Number(i.data.gasto||0),0))}</strong><span>Visível para CEO/Admin</span></article>}</div><h2 className="section-title">Situação das obras</h2><WorkCards items={obras} showMoney={canSeeMoney}/></>:active==="obras"?<><Toolbar title="Carteira nacional de obras" count={rows.length} action={add} label="Nova obra"/><WorkCards items={rows} showMoney={canSeeMoney} edit={edit} remove={remove}/></>:active==="relatorios"?<Reports exportar={exportar}/>:<><Toolbar title={config[active].title} count={rows.length} action={add} label={`Novo(a) ${config[active].singular}`}/>{active==="trabalhadores"&&<p className="section-note">Trabalhadores do Quadro, Consultores e Eventuais/Temporários.</p>}{active==="impedimentos"&&<p className="section-note warning">Área confidencial: apenas factos documentados, decisão autorizada e direito de resposta.</p>}<DataTable items={rows} fields={config[active].fields} edit={edit} remove={remove}/></>}</section></div>
}
function Toolbar({title,count,action,label}:{title:string;count:number;action:()=>void;label:string}){return <div className="module-toolbar"><div><h2>{title}</h2><span>{count} registos</span></div><button onClick={action}>+ {label}</button></div>}
function WorkCards({items,showMoney,edit,remove}:{items:Item[];showMoney:boolean;edit?:(i:Item)=>void;remove?:(i:Item)=>void}){return <div className="work-cards">{items.map(i=>{const p=Number(String(i.data.progresso||0).replace("%",""));return <article key={i.id}><header><span>{String(i.data.provincia||"Moçambique")}</span><em>{String(i.data.estado||"—")}</em></header><h3>{String(i.data.nome||"Obra")}</h3><p>{String(i.data.local||"—")}</p><div className="work-progress"><i style={{width:`${p}%`}}/></div><strong>{p}% executado</strong><dl><div><dt>Responsável</dt><dd>{String(i.data.responsavel||"—")}</dd></div><div><dt>Trabalhadores</dt><dd>{String(i.data.trabalhadores||0)}</dd></div></dl>{showMoney&&<p className="work-money">Gasto: <b>{money(Number(i.data.gasto||0))}</b></p>}{edit&&remove&&<div className="card-actions"><button onClick={()=>edit(i)}>Editar</button><button onClick={()=>remove(i)}>Apagar</button></div>}</article>})}</div>}
function DataTable({items,fields,edit,remove}:{items:Item[];fields:string[];edit:(i:Item)=>void;remove:(i:Item)=>void}){if(!items.length)return <div className="data-card empty-state"><strong>Ainda não existem registos.</strong><span>Use o botão “Novo” para adicionar.</span></div>;return <div className="data-card responsive-table"><table><thead><tr>{fields.map(f=><th key={f}>{f}</th>)}<th>Acções</th></tr></thead><tbody>{items.map(i=><tr key={i.id}>{fields.map(f=><td key={f}>{String(i.data[f]??"—")}</td>)}<td className="row-actions"><button onClick={()=>edit(i)}>Editar</button><button className="danger" onClick={()=>remove(i)}>Apagar</button></td></tr>)}</tbody></table></div>}
function Reports({exportar}:{exportar:()=>void}){return <div className="reports-grid">{["Ponto de situação das obras","Movimentação de trabalhadores","Utilização de equipamentos","Stock e consumo de materiais","Recursos Humanos","Base completa de gestão"].map((x,i)=><article key={x}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span><button onClick={exportar}>Gerar ↓</button></article>)}</div>}
