"use client";
import { useEffect,useMemo,useState } from "react";
type Item={id:string;module:string;data:Record<string,string|number>;updatedAt:string};
type Key="painel"|"obras"|"trabalhadores"|"equipamentos"|"materiais"|"movimentacoes"|"documentos"|"impedimentos"|"utilizadores"|"relatorios";
const config:Record<Exclude<Key,"painel"|"relatorios">,{title:string;singular:string;fields:string[]}> = {
 obras:{title:"Obras",singular:"obra",fields:["nome","local","provincia","estado","progresso","responsavel","trabalhadores","orcamento","gasto"]},
 trabalhadores:{title:"Recursos Humanos",singular:"trabalhador",fields:["nome","categoria","funcao","afectacao","provincia","contacto","estado"]},
 equipamentos:{title:"Equipamentos",singular:"equipamento",fields:["codigo","nome","tipo","afectacao","estado"]},
 materiais:{title:"Materiais",singular:"material",fields:["codigo","nome","unidade","quantidade","local"]},
 movimentacoes:{title:"Movimentações",singular:"movimentação",fields:["data","recurso","origem","destino","motivo"]},
 documentos:{title:"Gestão Documental",singular:"documento",fields:["codigo","titulo","categoria","obra","versao","responsavel","estado"]},
 impedimentos:{title:"Ocorrências Disciplinares",singular:"ocorrência",fields:["trabalhador","tipo","data","descricao","decisao","estado"]},
 utilizadores:{title:"Utilizadores",singular:"utilizador",fields:["nome","email","perfil","estado"]},
};
const labels:Record<Key,string>={painel:"Painel",obras:"Obras",equipamentos:"Equipamentos",materiais:"Materiais",trabalhadores:"Recursos Humanos",movimentacoes:"Movimentações",documentos:"Gestão Documental",impedimentos:"Ocorrências",utilizadores:"Utilizadores",relatorios:"Relatórios"};
const order:Key[]=["painel","obras","equipamentos","materiais","trabalhadores","movimentacoes","documentos","impedimentos","utilizadores","relatorios"];
const money=(v:number)=>new Intl.NumberFormat("pt-MZ",{style:"currency",currency:"MZN",maximumFractionDigits:0}).format(v);
const fieldLabels:Record<string,string>={nome:"Nome",local:"Local",provincia:"Província",estado:"Estado",progresso:"Progresso (%)",responsavel:"Responsável",trabalhadores:"N.º de trabalhadores",orcamento:"Orçamento (MZN)",gasto:"Valor gasto (MZN)",categoria:"Categoria",funcao:"Função",afectacao:"Afectação",contacto:"Contacto",codigo:"Código",tipo:"Tipo",unidade:"Unidade",quantidade:"Quantidade",data:"Data",recurso:"Recurso",origem:"Origem",destino:"Destino",motivo:"Motivo",titulo:"Título",obra:"Obra",versao:"Versão",trabalhador:"Trabalhador",descricao:"Descrição",decisao:"Decisão",email:"E-mail",perfil:"Perfil"};
const provinces=["Maputo Cidade","Maputo Província","Gaza","Inhambane","Sofala","Manica","Tete","Zambézia","Nampula","Cabo Delgado","Niassa"];
export default function GestaoClient(){
 const [active,setActive]=useState<Key>("painel"),[items,setItems]=useState<Item[]>([]),[role,setRole]=useState(""),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[q,setQ]=useState("");
 const [formOpen,setFormOpen]=useState(false),[editing,setEditing]=useState<Item|null>(null),[formData,setFormData]=useState<Record<string,string>>({}),[saving,setSaving]=useState(false);
 async function load(){setLoading(true);const r=await fetch("/api/gestao",{cache:"no-store"});if(r.ok){const x=await r.json();setItems(x.items);setRole(x.role)}else setMessage("A sua conta ainda não foi autorizada pelo Administrador.");setLoading(false)}
 useEffect(()=>{load()},[]);
 const rows=useMemo(()=>items.filter(i=>i.module===active&&JSON.stringify(i.data).toLowerCase().includes(q.toLowerCase())),[items,active,q]);
 const obras=items.filter(i=>i.module==="obras"),canSeeMoney=["ceo","administrador"].includes(role);
 const activeWorks=obras.filter(i=>!String(i.data.estado).toLowerCase().includes("conclu")),workers=obras.reduce((n,i)=>n+Number(i.data.trabalhadores||0),0),avg=activeWorks.length?Math.round(activeWorks.reduce((n,i)=>n+Number(String(i.data.progresso||0).replace("%","")),0)/activeWorks.length):0;
 function add(){if(active==="painel"||active==="relatorios")return;const data:Record<string,string>={};config[active].fields.forEach(f=>data[f]="");setEditing(null);setFormData(data);setFormOpen(true)}
 function edit(item:Item){const data:Record<string,string>={};config[active as Exclude<Key,"painel"|"relatorios">].fields.forEach(f=>data[f]=String(item.data[f]??""));setEditing(item);setFormData(data);setFormOpen(true)}
 function closeForm(){setFormOpen(false);setEditing(null);setFormData({})}
 async function submit(e:React.FormEvent){e.preventDefault();if(active==="painel"||active==="relatorios")return;setSaving(true);const url=editing?`/api/gestao/${editing.id}`:"/api/gestao",method=editing?"PUT":"POST";const body={module:active,data:formData};const r=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});setMessage(r.ok?(editing?"Registo actualizado.":"Registo guardado."):"Operação recusada. Confirme os dados e a sua permissão.");setSaving(false);if(r.ok){closeForm();await load()}}
 async function remove(item:Item){if(!confirm("Confirma que pretende apagar este registo?"))return;const r=await fetch(`/api/gestao/${item.id}`,{method:"DELETE"});setMessage(r.ok?"Registo apagado.":"Não foi possível apagar.");if(r.ok)await load()}
 function exportar(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(items,null,2)],{type:"application/json"}));a.download="base-khuumba.json";a.click()}
 return <div className="restored-shell"><aside className="restored-nav"><div><small>GESTÃO INTEGRADA</small><strong>{role||"Utilizador"}</strong></div>{order.map(k=><button className={active===k?"active":""} onClick={()=>{setActive(k);setFormOpen(false)}} key={k}>{labels[k]}</button>)}</aside><section className="restored-main"><header className="restored-header"><div><p className="eyebrow">PLATAFORMA KHUUMBA · BASE CENTRAL</p><h1>{labels[active]}</h1></div><div className="restored-actions"><input placeholder="Pesquisar…" value={q} onChange={e=>setQ(e.target.value)}/><button onClick={exportar}>Exportar base ↓</button></div></header>{message&&<p className="management-message">{message}</p>}{loading?<div className="data-card">A carregar dados…</div>:active==="painel"?<><div className="dashboard-kpis"><article><small>OBRAS ACTIVAS</small><strong>{activeWorks.length}</strong><span>{obras.length-activeWorks.length} concluídas</span></article><article><small>PROGRESSO MÉDIO</small><strong>{avg}%</strong><span>Obras em curso</span></article><article><small>TRABALHADORES</small><strong>{workers}</strong><span>Afectos às obras</span></article><article><small>EQUIPAMENTOS</small><strong>{items.filter(i=>i.module==="equipamentos").length}</strong><span>Inventário registado</span></article>{canSeeMoney&&<article className="financial-kpi"><small>VALOR GASTO</small><strong>{money(obras.reduce((n,i)=>n+Number(i.data.gasto||0),0))}</strong><span>Visível para CEO/Admin</span></article>}</div><h2 className="section-title">Situação das obras</h2><WorkCards items={obras} showMoney={canSeeMoney}/></>:active==="obras"?<><Toolbar title="Carteira nacional de obras" count={rows.length} action={add} label="Nova obra"/><WorkCards items={rows} showMoney={canSeeMoney} edit={edit} remove={remove}/></>:active==="relatorios"?<Reports exportar={exportar}/>:<><Toolbar title={config[active].title} count={rows.length} action={add} label={`Novo(a) ${config[active].singular}`}/>{active==="trabalhadores"&&<p className="section-note">Trabalhadores do Quadro, Consultores e Eventuais/Temporários.</p>}{active==="impedimentos"&&<p className="section-note warning">Área confidencial: apenas factos documentados, decisão autorizada e direito de resposta.</p>}<DataTable items={rows} fields={config[active].fields} edit={edit} remove={remove}/></>}</section>{formOpen&&active!=="painel"&&active!=="relatorios"&&<RecordForm module={active} data={formData} setData={setFormData} editing={!!editing} saving={saving} close={closeForm} submit={submit}/>}</div>
}
function RecordForm({module,data,setData,editing,saving,close,submit}:{module:Exclude<Key,"painel"|"relatorios">;data:Record<string,string>;setData:(v:Record<string,string>)=>void;editing:boolean;saving:boolean;close:()=>void;submit:(e:React.FormEvent)=>void}){const c=config[module];return <div className="form-overlay" role="dialog" aria-modal="true" aria-label={`${editing?"Editar":"Adicionar"} ${c.singular}`}><form className="record-form" onSubmit={submit}><header><div><small>{editing?"ACTUALIZAR REGISTO":"NOVO REGISTO"}</small><h2>{editing?"Editar":"Adicionar"} {c.singular}</h2></div><button type="button" onClick={close} aria-label="Fechar">×</button></header><div className="record-fields">{c.fields.map(f=><FormField key={f} field={f} value={data[f]||""} onChange={v=>setData({...data,[f]:v})}/>)}</div><footer><button type="button" className="cancel" onClick={close}>Cancelar</button><button type="submit" className="save" disabled={saving}>{saving?"A guardar…":editing?"Guardar alterações":"Guardar registo"}</button></footer></form></div>}
function FormField({field,value,onChange}:{field:string;value:string;onChange:(v:string)=>void}){const common={id:`field-${field}`,value,onChange:(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>)=>onChange(e.target.value),required:["nome","titulo","codigo","trabalhador","email"].includes(field)};let control:React.ReactNode;if(field==="provincia")control=<select {...common}><option value="">Seleccione a província</option>{provinces.map(x=><option key={x}>{x}</option>)}</select>;else if(field==="categoria")control=<select {...common}><option value="">Seleccione</option>{["Quadro","Consultor","Eventual/Temporário"].map(x=><option key={x}>{x}</option>)}</select>;else if(field==="perfil")control=<select {...common}><option value="">Seleccione</option>{["CEO","Administrador","Gestor de Obras","Financeiro","Logística","Trabalhador"].map(x=><option key={x}>{x}</option>)}</select>;else if(field==="estado")control=<select {...common}><option value="">Seleccione</option>{["Activo","Em execução","Mobilização","Concluída","Disponível","Em manutenção","Pendente","Arquivado","Suspenso"].map(x=><option key={x}>{x}</option>)}</select>;else if(field==="descricao"||field==="decisao"||field==="motivo")control=<textarea {...common} rows={3}/>;else control=<input {...common} type={field==="data"?"date":["progresso","trabalhadores","orcamento","gasto","quantidade"].includes(field)?"number":field==="email"?"email":field==="contacto"?"tel":"text"} min={field==="progresso"?0:undefined} max={field==="progresso"?100:undefined}/>;return <label className={["descricao","decisao","motivo"].includes(field)?"field-wide":""} htmlFor={`field-${field}`}><span>{fieldLabels[field]||field}</span>{control}</label>}
function Toolbar({title,count,action,label}:{title:string;count:number;action:()=>void;label:string}){return <div className="module-toolbar"><div><h2>{title}</h2><span>{count} registos</span></div><button onClick={action}>+ {label}</button></div>}
function WorkCards({items,showMoney,edit,remove}:{items:Item[];showMoney:boolean;edit?:(i:Item)=>void;remove?:(i:Item)=>void}){return <div className="work-cards">{items.map(i=>{const p=Number(String(i.data.progresso||0).replace("%",""));return <article key={i.id}><header><span>{String(i.data.provincia||"Moçambique")}</span><em>{String(i.data.estado||"—")}</em></header><h3>{String(i.data.nome||"Obra")}</h3><p>{String(i.data.local||"—")}</p><div className="work-progress"><i style={{width:`${p}%`}}/></div><strong>{p}% executado</strong><dl><div><dt>Responsável</dt><dd>{String(i.data.responsavel||"—")}</dd></div><div><dt>Trabalhadores</dt><dd>{String(i.data.trabalhadores||0)}</dd></div></dl>{showMoney&&<p className="work-money">Gasto: <b>{money(Number(i.data.gasto||0))}</b></p>}{edit&&remove&&<div className="card-actions"><button onClick={()=>edit(i)}>Editar</button><button onClick={()=>remove(i)}>Apagar</button></div>}</article>})}</div>}
function DataTable({items,fields,edit,remove}:{items:Item[];fields:string[];edit:(i:Item)=>void;remove:(i:Item)=>void}){if(!items.length)return <div className="data-card empty-state"><strong>Ainda não existem registos.</strong><span>Use o botão “Novo” para adicionar.</span></div>;return <div className="data-card responsive-table"><table><thead><tr>{fields.map(f=><th key={f}>{f}</th>)}<th>Acções</th></tr></thead><tbody>{items.map(i=><tr key={i.id}>{fields.map(f=><td key={f}>{String(i.data[f]??"—")}</td>)}<td className="row-actions"><button onClick={()=>edit(i)}>Editar</button><button className="danger" onClick={()=>remove(i)}>Apagar</button></td></tr>)}</tbody></table></div>}
function Reports({exportar}:{exportar:()=>void}){return <div className="reports-grid">{["Ponto de situação das obras","Movimentação de trabalhadores","Utilização de equipamentos","Stock e consumo de materiais","Recursos Humanos","Base completa de gestão"].map((x,i)=><article key={x}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span><button onClick={exportar}>Gerar ↓</button></article>)}</div>}
