"use client";
import {useEffect,useMemo,useState} from "react";
type User={nome:string;email:string;senha:string;perfil:string};
type Obra={id:string;nome:string;local:string;estado:string;progresso:number;responsavel:string;trabalhadores:number;equipamentos:string[]};
const users:User[]=[{nome:"António Mulenguene",email:"admin@khuumba.co.mz",senha:"CONFIGURE_ADMIN_PASSWORD",perfil:"Administrador"},{nome:"Celso Machava",email:"gestor@khuumba.co.mz",senha:"CONFIGURE_MANAGER_PASSWORD",perfil:"Gestor de Obras"},{nome:"Marta Cossa",email:"financeiro@khuumba.co.mz",senha:"CONFIGURE_FINANCE_PASSWORD",perfil:"Financeiro"},{nome:"Joaquim Mabote",email:"logistica@khuumba.co.mz",senha:"CONFIGURE_LOGISTICS_PASSWORD",perfil:"Logística"}];
const obras:Obra[]=[
 {id:"OBR-001",nome:"Obras na Portagem de Mudissa",local:"Mudissa, Província de Maputo",estado:"Em execução",progresso:10,responsavel:"Celso Machava",trabalhadores:18,equipamentos:["Camião Basculante 01","Pá Escavadora 01"]},
 {id:"OBR-002",nome:"Construção da Vala do Chiango",local:"Chiango, Cidade de Maputo",estado:"Concluída",progresso:100,responsavel:"Joaquim Langa",trabalhadores:0,equipamentos:[]},
 {id:"OBR-003",nome:"Obras na Portagem de Kumbeza",local:"Kumbeza, Província de Maputo",estado:"Concluída",progresso:100,responsavel:"Celso Machava",trabalhadores:0,equipamentos:[]},
 {id:"OBR-004",nome:"Obras na Portagem de Matola Gare",local:"Matola Gare, Província de Maputo",estado:"Em execução",progresso:90,responsavel:"Joaquim Langa",trabalhadores:26,equipamentos:["Camião Basculante 02","Betoneira 01"]},
 {id:"OBR-005",nome:"FIPAS — Gaza",local:"Província de Gaza",estado:"Mobilização",progresso:5,responsavel:"Alberto Bila",trabalhadores:12,equipamentos:["Viatura Operacional 01"]},
 {id:"OBR-006",nome:"FIPAS — Inhambane",local:"Província de Inhambane",estado:"Mobilização",progresso:5,responsavel:"Marta Nhantumbo",trabalhadores:10,equipamentos:["Camião de Apoio 01"]},
 {id:"OBR-007",nome:"FIPAS — Maputo Província",local:"Província de Maputo",estado:"Mobilização",progresso:5,responsavel:"Alberto Bila",trabalhadores:14,equipamentos:["Viatura Operacional 02"]}
];
const equipamentos=[
 ["EQ-001","Camião Basculante 01","Camião","Mudissa","Operacional"],["EQ-002","Camião Basculante 02","Camião","Matola Gare","Operacional"],["EQ-003","Camião de Apoio 01","Camião","FIPAS Inhambane","Em missão"],["EQ-004","Pá Escavadora 01","Máquina pesada","Mudissa","Operacional"],["EQ-005","Pá Escavadora 02","Máquina pesada","Estaleiro Central","Disponível"],["EQ-006","Betoneira 01","Equipamento","Matola Gare","Operacional"],["EQ-007","Viatura Operacional 01","Pickup","FIPAS Gaza","Em missão"],["EQ-008","Viatura Operacional 02","Pickup","FIPAS Maputo","Em missão"],["EQ-009","Gerador 01","Energia","Estaleiro Central","Disponível"]
];
const materiais=[["MAT-001","Cimento 42.5","Saco",680,"Armazém Central"],["MAT-002","Ferro 12 mm","Barra",420,"Mudissa"],["MAT-003","Brita","m³",185,"Matola Gare"],["MAT-004","Areia lavada","m³",240,"Matola Gare"],["MAT-005","Tubagem PVC","Unidade",310,"FIPAS Gaza"],["MAT-006","Blocos","Unidade",4800,"Mudissa"],["MAT-007","Combustível","Litro",3450,"Armazém Central"]];
const movimentos=[["19/07/2026","18 trabalhadores","Sede → Mudissa","Mobilização de equipa"],["19/07/2026","12 trabalhadores","Maputo → FIPAS Gaza","Mobilização inicial"],["18/07/2026","10 trabalhadores","Maputo → FIPAS Inhambane","Mobilização inicial"],["18/07/2026","14 trabalhadores","Sede → FIPAS Maputo","Mobilização inicial"],["17/07/2026","8 trabalhadores","Matola Gare → Sede","Rotação de equipa"],["16/07/2026","Pá Escavadora 01","Estaleiro → Mudissa","Afectação de equipamento"]];
function dbGet<T>(k:string,d:T):T{if(typeof window==="undefined")return d;try{const value=JSON.parse(localStorage.getItem(k)||"");return value??d}catch{return d}}
export default function Gestao(){const [user,setUser]=useState<User|null>(users[0]),[email,setEmail]=useState("admin@khuumba.co.mz"),[senha,setSenha]=useState("CONFIGURE_ADMIN_PASSWORD"),[erro,setErro]=useState(""),[tab,setTab]=useState("Painel"),[lista,setLista]=useState<Obra[]>(obras),[q,setQ]=useState("");useEffect(()=>{const seed="khuumba-demo-v4";if(localStorage.getItem("khuumba-seed")!==seed){localStorage.setItem("khuumba-seed",seed);localStorage.setItem("khuumba-obras",JSON.stringify(obras));localStorage.setItem("khuumba-user",JSON.stringify(users[0]));setLista(obras);setUser(users[0]);return}const saved=dbGet<Obra[]>("khuumba-obras",obras);setLista(Array.isArray(saved)&&saved.length?saved:obras);const savedUser=dbGet<User|null>("khuumba-user",users[0]);setUser(savedUser?.nome?savedUser:users[0])},[]);useEffect(()=>{if(user)localStorage.setItem("khuumba-user",JSON.stringify(user));localStorage.setItem("khuumba-obras",JSON.stringify(lista))},[user,lista]);function login(e:React.FormEvent){e.preventDefault();const u=users.find(x=>x.email===email&&x.senha===senha);if(u){setUser(u);setErro("")}else setErro("E-mail ou senha inválidos.")}function logout(){localStorage.removeItem("khuumba-user");setUser(null)}function reporDemo(){localStorage.setItem("khuumba-obras",JSON.stringify(obras));setLista(obras);setQ("");setTab("Painel")}function exportar(){const blob=new Blob([JSON.stringify({obras:lista,equipamentos,materiais,movimentos,utilizadores:users.map(({senha,...u})=>u)},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="base-khuumba.json";a.click()}if(!user)return <main className="glogin"><section><a href="/" className="gloginlogo"><b>K</b><span>KHUUMBA<small>SISTEMA DE GESTÃO DE OBRAS</small></span></a><h1>Bem-vindo</h1><p>Aceda à base de gestão operacional da KHUUMBA.</p><form onSubmit={login}><label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)} type="email"/></label><label>Senha<input value={senha} onChange={e=>setSenha(e.target.value)} type="password"/></label>{erro&&<em>{erro}</em>}<button>Entrar no sistema</button></form><button className="demoenter" onClick={()=>setUser(users[0])}>Abrir demonstração com dados</button><div className="demologin"><b>O ambiente demonstrativo inclui</b><span>7 obras, 9 equipamentos, 7 materiais e movimentações operacionais.</span></div></section><aside><strong>Gestão integrada.</strong><h2>Obras, pessoas, materiais e equipamentos num único lugar.</h2><p>Construímos soluções. Transformamos comunidades.</p></aside></main>;
 const mods=["Painel","Obras","Equipamentos","Materiais","Trabalhadores","Movimentações","Utilizadores","Relatórios"];const filtradas=lista.filter(x=>(x.nome+x.local+x.estado).toLowerCase().includes(q.toLowerCase()));return <main className="gshell"><aside><a href="/" className="glogo"><b>K</b><span>KHUUMBA<small>GESTÃO DE OBRAS</small></span></a><nav>{mods.map(x=><button className={tab===x?"on":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><div className="guser"><b>{user.nome.split(" ").map(x=>x[0]).slice(0,2)}</b><span>{user.nome}<small>{user.perfil}</small></span><button onClick={logout}>Sair</button></div></aside><section className="gmain"><header><div><small>BASE OPERACIONAL KHUUMBA · DADOS SIMULADOS</small><h1>{tab}</h1></div><div className="gactions"><input placeholder="Pesquisar..." value={q} onChange={e=>setQ(e.target.value)}/><button onClick={reporDemo}>Repor dados</button><button onClick={exportar}>Exportar base ↓</button><a href="/">Portal ↗</a></div></header>{tab==="Painel"&&<Painel lista={lista}/>} {tab==="Obras"&&<Obras lista={filtradas}/>} {tab==="Equipamentos"&&<Tabela title="Inventário de equipamentos" headers={["Código","Equipamento","Tipo","Afectação","Estado"]} rows={equipamentos}/>} {tab==="Materiais"&&<Tabela title="Stock e materiais" headers={["Código","Material","Unidade","Quantidade","Local"]} rows={materiais}/>} {tab==="Trabalhadores"&&<Trabalhadores/>} {tab==="Movimentações"&&<Tabela title="Movimentações operacionais" headers={["Data","Recurso","Origem / Destino","Motivo"]} rows={movimentos}/>} {tab==="Utilizadores"&&<Tabela title="Utilizadores do sistema" headers={["Nome","E-mail","Perfil"]} rows={users.map(x=>[x.nome,x.email,x.perfil])}/>} {tab==="Relatórios"&&<Relatorios lista={lista} exportar={exportar}/>}</section></main>}
function Painel({lista}:{lista:Obra[]}){const activos=lista.filter(x=>x.progresso<100),media=Math.round(activos.reduce((a,b)=>a+b.progresso,0)/activos.length),trab=lista.reduce((a,b)=>a+b.trabalhadores,0);return <><div className="gnote"><b>Base demonstrativa operacional</b> — cenários de obras, recursos e movimentações preparados para validação.</div><div className="gkpis"><article><small>OBRAS ACTIVAS</small><strong>{activos.length}</strong><span>2 concluídas</span></article><article><small>PROGRESSO MÉDIO</small><strong>{media}%</strong><span>Obras em curso</span></article><article><small>TRABALHADORES</small><strong>{trab}</strong><span>Afectos às obras activas</span></article><article><small>EQUIPAMENTOS</small><strong>{equipamentos.length}</strong><span>7 em operação/missão</span></article></div><Obras lista={lista}/><div className="gsummary"><article><h3>Estado das obras</h3>{[["Concluídas",2],["Em execução",2],["Mobilização",3]].map(x=><p key={String(x[0])}><span>{x[0]}</span><b>{x[1]}</b></p>)}</article><article><h3>Recursos em campo</h3><p><span>Camiões e viaturas</span><b>5</b></p><p><span>Máquinas e equipamentos</span><b>4</b></p><p><span>Materiais registados</span><b>{materiais.length}</b></p></article><article><h3>Alertas operacionais</h3><p><span>Matola Gare próxima da conclusão</span><b>90%</b></p><p><span>FIPAS em mobilização</span><b>3</b></p><p><span>Equipamento disponível</span><b>2</b></p></article></div></>}
function Obras({lista}:{lista:Obra[]}){return <div className="gcards">{lista.map(x=><article key={x.id}><header><span>{x.id}</span><em>{x.estado}</em></header><h3>{x.nome}</h3><p>{x.local}</p><div className="bigprogress"><i style={{width:x.progresso+"%"}}/></div><strong>{x.progresso}% executado</strong><dl><div><dt>Responsável</dt><dd>{x.responsavel}</dd></div><div><dt>Trabalhadores</dt><dd>{x.trabalhadores}</dd></div><div><dt>Equipamentos</dt><dd>{x.equipamentos.length}</dd></div></dl></article>)}</div>}
function Tabela({title,headers,rows}:{title:string;headers:string[];rows:(string|number)[][]}){return <div className="gtable"><div><h2>{title}</h2><span>{rows.length} registos</span></div><table><thead><tr>{headers.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>}
function Trabalhadores(){const rows=[["TR-001","Paulo Matavele","Encarregado","Mudissa","Em campo"],["TR-002","Ernesto Mucavele","Operador de máquina","Mudissa","Em campo"],["TR-003","Ana Mondlane","Engenheira Civil","Matola Gare","Em campo"],["TR-004","Carlos Muianga","Técnico de Segurança","Matola Gare","Em campo"],["TR-005","Marta Nhantumbo","Coordenadora","FIPAS Inhambane","Em missão"],["TR-006","Alberto Bila","Coordenador","FIPAS Gaza/Maputo","Em missão"]];return <Tabela title="Trabalhadores e afectação" headers={["Código","Nome","Função","Afectação","Situação"]} rows={rows}/>}
function Relatorios({lista,exportar}:{lista:Obra[];exportar:()=>void}){return <div className="greports"><h2>Centro de relatórios</h2><p>Gere informação consolidada para acompanhamento e decisão.</p><div>{["Ponto de situação das obras","Movimentação de trabalhadores","Utilização de equipamentos","Stock e consumo de materiais","Obras concluídas","Base completa de gestão"].map((x,i)=><article key={x}><b>{String(i+1).padStart(2,"0")}</b><span>{x}</span><button onClick={exportar}>Gerar ↓</button></article>)}</div></div>}
